version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env

# .env
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USERNAME=sajibnet@gmail.com
# SMTP_PASSWORD=your-secret-password
# RECEIVING_EMAIL_ADDRESS=reciveing email@gmail.com