
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    restart: always
